### ISSUE TITLE
Mejorar funcion write_info()

### ISSUE THREAD

**Issue by glacayo** [glacayo/websitecreator#1]
Mejorar la funcion write_info(), falta procesar los colores, y agregar la variable "getfull_name" original del archivo text.

**Comment by glacayo** [comment]
falta también sincronizar los nombres de los fields del index en la recepción de las variables en el archivo websiteCreator.php

**Comment by yerespinoza** [comment]
Con respecto a los colores se agregara al Css.php una condicional para seleccionar cualquiera de las 10 hojas de estilos que se agregaran para la selección de las Paletas de Colores.

**Comment by glacayo** [comment]
Write function mejorada, ya escribe toda la informacion necesaria en el text.php
